/**
 * build-roads.mjs
 * ---------------------------------------------------------------------------
 * Bakes the real street network around the study corridor.
 *
 * Figueroa on its own, floating on an empty plane, reads as a diagram rather
 * than a place. What makes downtown look like downtown is everything AROUND
 * the street: the grid of cross streets, the 110 ramps curling in from the
 * west, the sidewalks, the alleys behind the towers, Pershing Square.
 *
 * All of it is real OpenStreetMap geometry in the same metre grid as the
 * buildings and the roadway, so nothing has to be placed by eye.
 *
 * South Figueroa itself is excluded — it gets its own mesh, with lane markings
 * and traffic, and drawing it twice would z-fight.
 *
 * Fetch the input with:
 *
 *   curl -G https://overpass-api.de/api/interpreter -A "your-project/1.0" \
 *     --data-urlencode 'data=[out:json][timeout:120];(way["highway"](34.0420,-118.2690,34.0570,-118.2520);way["leisure"="park"](...);way["landuse"~"^(grass|recreation_ground)$"](...););out tags geom;' \
 *     -o osm-roads.json
 *
 * then run:  node scripts/build-roads.mjs osm-roads.json
 */

import { readFileSync, writeFileSync } from 'node:fs';

const ORIGIN = { lat: 34.049, lon: -118.2585 };
const M_PER_DEG_LAT = 110574;
const M_PER_DEG_LON = 111320 * Math.cos((ORIGIN.lat * Math.PI) / 180);

const project = (lat, lon) => [
  (lon - ORIGIN.lon) * M_PER_DEG_LON,
  -(lat - ORIGIN.lat) * M_PER_DEG_LAT,
];

/**
 * Carriageway width by road class, metres. These are the width of the paved
 * surface, not the right of way — a downtown "primary" is four to six lanes.
 */
const WIDTH = {
  motorway: 24,
  trunk: 19,
  primary: 16,
  secondary: 14,
  tertiary: 11,
  residential: 9.5,
  unclassified: 9,
  living_street: 7.5,
  service: 5,
  pedestrian: 6.5,
  footway: 2.4,
  motorway_link: 8,
  trunk_link: 8,
  primary_link: 7,
  secondary_link: 7,
};

/** Render tier, so the scene can shade big roads differently from alleys. */
function tierOf(hw) {
  if (hw === 'motorway' || hw === 'trunk' || hw.endsWith('_link')) return 'highway';
  if (hw === 'primary' || hw === 'secondary' || hw === 'tertiary') return 'major';
  if (hw === 'footway' || hw === 'pedestrian') return 'path';
  return 'minor';
}

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('usage: node scripts/build-roads.mjs <osm-roads.json>');
  process.exit(1);
}

const raw = JSON.parse(readFileSync(inputPath, 'utf8'));
const elements = raw.elements ?? [];

const roads = [];
const areas = [];
const counts = {};
let skipped = 0;

for (const el of elements) {
  if (!el.geometry || el.geometry.length < 2) continue;
  const tags = el.tags ?? {};

  // green space, as a filled polygon
  if (tags.leisure === 'park' || tags.landuse === 'grass' || tags.landuse === 'recreation_ground') {
    if (el.geometry.length < 4) continue;
    areas.push({
      k: tags.leisure === 'park' ? 'park' : 'grass',
      p: el.geometry.map((g) => project(g.lat, g.lon).map((v) => Math.round(v * 10) / 10)),
    });
    continue;
  }

  const hw = tags.highway;
  if (!hw || !(hw in WIDTH)) continue;

  // Figueroa gets its own mesh with lane markings and traffic.
  if (/south figueroa/i.test(tags.name ?? '')) continue;

  const pts = el.geometry.map((g) => project(g.lat, g.lon));

  // drop hairline fragments: they cost geometry and show nothing
  let len = 0;
  for (let i = 1; i < pts.length; i++) {
    len += Math.hypot(pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]);
  }
  if (len < (hw === 'footway' ? 12 : 6)) {
    skipped++;
    continue;
  }

  const tier = tierOf(hw);
  counts[tier] = (counts[tier] ?? 0) + 1;

  roads.push({
    t: tier,
    w: WIDTH[hw],
    p: pts.map(([x, z]) => [Math.round(x * 10) / 10, Math.round(z * 10) / 10]),
  });
}

const out = {
  note: 'Real OpenStreetMap street network and green space around South Figueroa. Projected to metres about the origin below. Generated by scripts/build-roads.mjs — do not edit by hand.',
  origin: ORIGIN,
  generated: new Date().toISOString().slice(0, 10),
  roads,
  areas,
};

writeFileSync('src/data/roads.json', JSON.stringify(out));

console.log(`roads kept : ${roads.length}`);
console.log(`  by tier  : ${JSON.stringify(counts)}`);
console.log(`areas      : ${areas.length}`);
console.log(`skipped    : ${skipped} (too short)`);
