/**
 * build-street.mjs
 * ---------------------------------------------------------------------------
 * Stitches the real OpenStreetMap centreline of South Figueroa Street into a
 * single ordered polyline for the study corridor.
 *
 * WHY THIS EXISTS
 *
 * The first version of this project used a hand-estimated line of
 * intersections as the street's spine. It was close, but "close" in a city is
 * forty metres, and forty metres puts the roadway inside the lobby of the
 * Wilshire Grand. Since the buildings are real OSM geometry, the street has to
 * be real OSM geometry too, or the two will not line up.
 *
 * OSM stores Figueroa as several dozen short ways, one per block or turn
 * pocket, in no particular order. Over this stretch the street is monotonic in
 * latitude, so sorting the points north to south puts them back in sequence
 * without needing to solve the general way-stitching problem.
 *
 * Fetch the input with:
 *
 *   curl -G https://overpass-api.de/api/interpreter -A "your-project/1.0" \
 *     --data-urlencode 'data=[out:json][timeout:90];way["highway"]["name"~"Figueroa",i](34.0400,-118.2700,34.0600,-118.2500);out tags geom;' \
 *     -o osm-fig.json
 *
 * then run:  node scripts/build-street.mjs osm-fig.json
 */

import { readFileSync, writeFileSync } from 'node:fs';

/** The study corridor: 3rd Street down to 11th. */
const LAT_NORTH = 34.0556;
const LAT_SOUTH = 34.0433;

const inputPath = process.argv[2];
if (!inputPath) {
  console.error('usage: node scripts/build-street.mjs <osm-fig.json>');
  process.exit(1);
}

const raw = JSON.parse(readFileSync(inputPath, 'utf8'));
const ways = (raw.elements ?? []).filter(
  (e) => e.geometry && /south figueroa/i.test(e.tags?.name ?? ''),
);

/** Every point on every South Figueroa way, inside the study range. */
const points = [];
const laneSamples = [];

for (const w of ways) {
  const lanes = Number(w.tags?.lanes);
  for (const g of w.geometry) {
    if (g.lat > LAT_NORTH || g.lat < LAT_SOUTH) continue;
    points.push({ lat: g.lat, lon: g.lon });
    if (Number.isFinite(lanes)) laneSamples.push({ lat: g.lat, lanes });
  }
}

// North to south — the direction of travel we study.
points.sort((a, b) => b.lat - a.lat);

// Figueroa is dual-carriageway in places, so two points at the same latitude
// can be the two directions. Collapse anything closer than 8 m into one point
// at their mean, which puts the centreline between the carriageways.
const M_PER_DEG_LAT = 110574;
const M_PER_DEG_LON = 111320 * Math.cos((34.049 * Math.PI) / 180);
const dist = (a, b) =>
  Math.hypot((a.lat - b.lat) * M_PER_DEG_LAT, (a.lon - b.lon) * M_PER_DEG_LON);

const merged = [];
for (const p of points) {
  const last = merged[merged.length - 1];
  if (last && dist(last, p) < 8) {
    last.lat = (last.lat + p.lat) / 2;
    last.lon = (last.lon + p.lon) / 2;
    last.n++;
  } else {
    merged.push({ ...p, n: 1 });
  }
}

// A light smoothing pass: OSM nodes cluster at intersections and the raw line
// can kink by a metre or two where ways meet.
const smoothed = merged.map((p, i) => {
  if (i === 0 || i === merged.length - 1) return { lat: p.lat, lon: p.lon };
  const a = merged[i - 1];
  const b = merged[i + 1];
  return {
    lat: (a.lat + p.lat * 2 + b.lat) / 4,
    lon: (a.lon + p.lon * 2 + b.lon) / 4,
  };
});

let length = 0;
for (let i = 1; i < smoothed.length; i++) length += dist(smoothed[i - 1], smoothed[i]);

/** Representative lane count, by thirds of the corridor. */
function lanesNear(lat) {
  const near = laneSamples
    .map((s) => ({ ...s, d: Math.abs(s.lat - lat) }))
    .sort((a, b) => a.d - b.d)
    .slice(0, 5);
  if (!near.length) return null;
  const sorted = near.map((s) => s.lanes).sort((a, b) => a - b);
  return sorted[Math.floor(sorted.length / 2)];
}

const out = {
  note: 'Real OpenStreetMap centreline of South Figueroa Street, 3rd to 11th, ordered north to south. Generated by scripts/build-street.mjs — do not edit by hand.',
  generated: new Date().toISOString().slice(0, 10),
  lengthMetres: Math.round(length),
  points: smoothed.map((p) => [
    Number(p.lat.toFixed(6)),
    Number(p.lon.toFixed(6)),
  ]),
};

writeFileSync('src/data/street.json', JSON.stringify(out));

console.log(`ways matched  : ${ways.length}`);
console.log(`raw points    : ${points.length}`);
console.log(`centreline    : ${smoothed.length} points`);
console.log(`length        : ${out.lengthMetres} m (${(out.lengthMetres / 1609.344).toFixed(2)} mi)`);
console.log(`north end     : ${smoothed[0]?.lat.toFixed(5)}, ${smoothed[0]?.lon.toFixed(5)}`);
console.log(`south end     : ${smoothed[smoothed.length - 1]?.lat.toFixed(5)}, ${smoothed[smoothed.length - 1]?.lon.toFixed(5)}`);
console.log(`lanes @ 3rd   : ${lanesNear(34.0553)}`);
console.log(`lanes @ 7th   : ${lanesNear(34.0486)}`);
console.log(`lanes @ 11th  : ${lanesNear(34.0437)}`);
